# -*- coding: utf-8 -*-
"""zero shot prompt.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZkaPmFeo1MSStnQwhAhu9oLt2rZcd79o
"""

!pip install groq --quiet

print("✅ Groq installed!")

# ============================================
# CELL 2: GROQ API KEY
# ============================================

from groq import Groq
import os

# Paste your key here between the quotes
GROQ_API_KEY = "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"

os.environ["GROQ_API_KEY"] = GROQ_API_KEY
client = Groq(api_key=GROQ_API_KEY)

# Test connection
test = client.chat.completions.create(
    model="llama-3.1-8b-instant",
    messages=[{"role": "user", "content": "Say hello in one word"}],
    max_tokens=5
)
print("✅ Groq connected!")
print(f"Test response: {test.choices[0].message.content}")

# ============================================
# CELL 3: UPLOAD ENGLISH TEST SET
# ============================================

from google.colab import files
import pandas as pd
import numpy as np
import os
import time
import json
import warnings
warnings.filterwarnings('ignore')

print("Upload your English test CSV file:")
uploaded = files.upload()

TEST_FILE = list(uploaded.keys())[0]
df_test = pd.read_csv(TEST_FILE)

# ---- Change these if your column names are different ----
TEXT_COL = "headline"
LABEL_COL = "label"

print(f"\n✅ File loaded: {TEST_FILE}")
print(f"Total samples: {len(df_test)}")
print(f"Columns: {list(df_test.columns)}")
print(f"Clickbait: {sum(df_test[LABEL_COL]==1)}")
print(f"Non-Clickbait: {sum(df_test[LABEL_COL]==0)}")
print(f"\nPreview:")
print(df_test.head(3))

# ============================================
# CELL 4: CONFIGURATION, MODELS AND PROMPTS
# ============================================

SEED = 42
RESULTS_DIR = "groq_llm_results"
os.makedirs(RESULTS_DIR, exist_ok=True)

# ============================================
# MODELS TO EVALUATE — LLaMA + Mistral
# ============================================
MODELS = {
    "LLaMA-3.1-8B": "llama-3.1-8b-instant",
    "Mistral-7B": "mixtral-8x7b-32768"            # Updated from "mistral-saba-24b" to a valid model
}

# ============================================
# THREE PROMPT TEMPLATES (Same as before)
# ============================================

P1_DIRECT = """Classify the following news headline as either "Clickbait" or "Not Clickbait".
Only output the exact label. Do not write any explanation.

Headline: {headline}

Label:"""

P2_CONCISE = """Is this headline clickbait? Answer only "Clickbait" or "Not Clickbait".

Headline: {headline}

Answer:"""

P3_DESCRIPTIVE = """You are a news headline classifier. Determine if the headline is clickbait (sensationalized, misleading, exaggerated to attract clicks) or not clickbait (genuine, informative, straightforward).

Respond with exactly one label: "Clickbait" or "Not Clickbait". No other text.

Headline: {headline}

Label:"""

PROMPTS = {
    "P1_direct": P1_DIRECT,
    "P2_concise": P2_CONCISE,
    "P3_descriptive": P3_DESCRIPTIVE
}

print("✅ Configuration loaded!")
print(f"\nModels to evaluate:")
for name, model_id in MODELS.items():
    print(f"  - {name}: {model_id}")
print(f"\nPrompts to evaluate:")
for name in PROMPTS.keys():
    print(f"  - {name}")
print(f"\nResults folder: {RESULTS_DIR}/")

# ============================================
# CELL 5: ALL FUNCTIONS
# ============================================

from sklearn.metrics import (
    accuracy_score, precision_score,
    recall_score, f1_score,
    confusion_matrix, classification_report
)
import matplotlib.pyplot as plt
import seaborn as sns


# ============================================
# GROQ API CALL
# ============================================

def generate_label(headline, prompt_template, model_id, max_retries=3):
    """Call Groq API for a single headline"""

    prompt = prompt_template.format(headline=str(headline))

    for attempt in range(max_retries):
        try:
            response = client.chat.completions.create(
                model=model_id,
                messages=[
                    {
                        "role": "user",
                        "content": prompt
                    }
                ],
                max_tokens=10,
                temperature=0.0,
                top_p=1.0,
                stream=False
            )
            return response.choices[0].message.content.strip()

        except Exception as e:
            error_msg = str(e)

            # Rate limit error — wait and retry
            if "rate_limit" in error_msg.lower() or "429" in error_msg:
                wait_time = 10 * (attempt + 1)
                print(f"\n  ⚠️ Rate limit hit. Waiting {wait_time}s...")
                time.sleep(wait_time)

            # Other error
            else:
                print(f"\n  ⚠️ API Error (attempt {attempt+1}): {error_msg[:50]}")
                time.sleep(3)

    return "ERROR"


# ============================================
# LABEL PARSER
# ============================================

def parse_label(raw_output):
    """Parse model output to binary label"""

    output_lower = raw_output.lower().strip()

    # Check Not Clickbait first (important order)
    if "not clickbait" in output_lower or "not_clickbait" in output_lower:
        return 0    # Non-clickbait
    elif "clickbait" in output_lower:
        return 1    # Clickbait
    else:
        return -1   # Unparseable


# ============================================
# MAIN INFERENCE FUNCTION
# ============================================

def run_inference(headlines, true_labels, prompt_template,
                  model_name, model_id, prompt_name):
    """Run zero-shot inference on all samples"""

    print(f"\n{'='*65}")
    print(f"  Model:   {model_name} ({model_id})")
    print(f"  Prompt:  {prompt_name}")
    print(f"  Samples: {len(headlines)}")
    print(f"{'='*65}")

    predictions = []
    raw_outputs = []
    unparseable_count = 0
    unparseable_samples = []
    start_time = time.time()

    for i, headline in enumerate(headlines):

        # Call API
        raw = generate_label(headline, prompt_template, model_id)
        raw_outputs.append(raw)

        # Parse output
        pred = parse_label(raw)

        # Handle unparseable
        if pred == -1:
            unparseable_count += 1
            unparseable_samples.append({
                "index": i,
                "headline": str(headline),
                "raw_output": raw
            })
            # Count as wrong prediction (conservative)
            pred = 1 - int(true_labels[i])

        predictions.append(pred)

        # Small delay to respect rate limits
        time.sleep(0.1)

        # Progress update every 100 samples
        if (i + 1) % 100 == 0 or (i + 1) == len(headlines):
            elapsed = time.time() - start_time
            speed = (i + 1) / elapsed
            eta = (len(headlines) - i - 1) / speed if speed > 0 else 0
            print(f"  [{i+1}/{len(headlines)}] "
                  f"Speed: {speed:.1f}/s | "
                  f"ETA: {eta/60:.1f} min | "
                  f"Unparseable: {unparseable_count}")

    total_time = time.time() - start_time
    predictions = np.array(predictions)
    true_labels_arr = np.array(true_labels, dtype=int)

    # ---- Calculate All Metrics ----
    acc = accuracy_score(true_labels_arr, predictions)
    prec = precision_score(true_labels_arr, predictions, average='macro', zero_division=0)
    rec = recall_score(true_labels_arr, predictions, average='macro', zero_division=0)
    f1 = f1_score(true_labels_arr, predictions, average='macro', zero_division=0)
    cm = confusion_matrix(true_labels_arr, predictions)
    f1_per = f1_score(true_labels_arr, predictions, average=None, zero_division=0)

    # Per class precision and recall
    prec_per = precision_score(true_labels_arr, predictions, average=None, zero_division=0)
    rec_per = recall_score(true_labels_arr, predictions, average=None, zero_division=0)

    result = {
        "model_name": model_name,
        "model_id": model_id,
        "prompt": prompt_name,
        "accuracy": round(acc * 100, 2),
        "precision_macro": round(prec * 100, 2),
        "recall_macro": round(rec * 100, 2),
        "f1_macro": round(f1 * 100, 2),
        "f1_non_clickbait": round(f1_per[0] * 100, 2) if len(f1_per) > 0 else 0,
        "f1_clickbait": round(f1_per[1] * 100, 2) if len(f1_per) > 1 else 0,
        "precision_non_clickbait": round(prec_per[0] * 100, 2) if len(prec_per) > 0 else 0,
        "precision_clickbait": round(prec_per[1] * 100, 2) if len(prec_per) > 1 else 0,
        "recall_non_clickbait": round(rec_per[0] * 100, 2) if len(rec_per) > 0 else 0,
        "recall_clickbait": round(rec_per[1] * 100, 2) if len(rec_per) > 1 else 0,
        "confusion_matrix": cm.tolist(),
        "unparseable_count": unparseable_count,
        "unparseable_rate": round(unparseable_count / len(headlines) * 100, 2),
        "total_time_s": round(total_time, 2),
        "inference_time_ms": round(total_time * 1000 / len(headlines), 2),
        "total_samples": len(headlines)
    }

    # ---- Print Results ----
    print(f"\n  {'─'*55}")
    print(f"  ✅ RESULTS: {model_name} | {prompt_name}")
    print(f"  {'─'*55}")
    print(f"  Accuracy:          {result['accuracy']}%")
    print(f"  Precision (Macro): {result['precision_macro']}%")
    print(f"  Recall (Macro):    {result['recall_macro']}%")
    print(f"  F1 (Macro):        {result['f1_macro']}%")
    print(f"  F1 (Clickbait):    {result['f1_clickbait']}%")
    print(f"  F1 (Non-CB):       {result['f1_non_clickbait']}%")
    print(f"  Unparseable:       {result['unparseable_count']} ({result['unparseable_rate']}%)")
    print(f"  Total Time:        {result['total_time_s']}s")
    print(f"  Per Sample:        {result['inference_time_ms']} ms/sample")
    print(f"\n  Confusion Matrix:")
    print(f"  {cm}")

    return result, predictions, raw_outputs, unparseable_samples


# ============================================
# CONFUSION MATRIX PLOT
# ============================================

def plot_cm(cm_array, model_name, prompt_name, accuracy):
    """Plot and save confusion matrix"""

    plt.figure(figsize=(6, 5))
    sns.heatmap(
        cm_array,
        annot=True,
        fmt='d',
        cmap='Blues',
        xticklabels=['Non-Clickbait', 'Clickbait'],
        yticklabels=['Non-Clickbait', 'Clickbait']
    )
    plt.title(f'{model_name} — {prompt_name}\nAccuracy: {accuracy}%')
    plt.ylabel('Actual')
    plt.xlabel('Predicted')
    plt.tight_layout()

    safe_model = model_name.replace(" ", "_").replace("-", "_").lower()
    safe_prompt = prompt_name.replace(" ", "_").lower()
    save_path = f"{RESULTS_DIR}/cm_{safe_model}_{safe_prompt}.png"
    plt.savefig(save_path, dpi=150)
    plt.show()
    plt.close()
    print(f"  💾 Saved: {save_path}")


# ============================================
# COMPARISON BAR CHART
# ============================================

def plot_comparison(results_list, title, save_name):
    """Plot bar chart comparing models"""

    labels = [f"{r['model_name']}\n({r['prompt']})" for r in results_list]
    accuracies = [r['accuracy'] for r in results_list]
    f1_scores = [r['f1_macro'] for r in results_list]

    x = np.arange(len(labels))
    width = 0.35

    fig, ax = plt.subplots(figsize=(12, 6))
    bars1 = ax.bar(x - width/2, accuracies, width, label='Accuracy', color='#2196F3')
    bars2 = ax.bar(x + width/2, f1_scores, width, label='F1 Macro', color='#4CAF50')

    # Add value labels
    for bar in bars1:
        ax.text(bar.get_x() + bar.get_width()/2, bar.get_height() + 0.3,
                f'{bar.get_height()}%', ha='center', va='bottom', fontsize=9)
    for bar in bars2:
        ax.text(bar.get_x() + bar.get_width()/2, bar.get_height() + 0.3,
                f'{bar.get_height()}%', ha='center', va='bottom', fontsize=9)

    ax.set_xlabel('Model and Prompt')
    ax.set_ylabel('Score (%)')
    ax.set_title(title)
    ax.set_xticks(x)
    ax.set_xticklabels(labels, fontsize=9)
    ax.legend()
    ax.set_ylim(0, 110)
    ax.grid(axis='y', alpha=0.3)

    plt.tight_layout()
    save_path = f"{RESULTS_DIR}/{save_name}.png"
    plt.savefig(save_path, dpi=150)
    plt.show()
    plt.close()
    print(f"  💾 Chart saved: {save_path}")


print("✅ All functions loaded and ready!")

# ============================================
# CELL 6: PHASE 1 — PROMPT EVALUATION
# Test all 3 prompts with both models
# on 200 sample subset
# ============================================

print("=" * 65)
print("  PHASE 1: PROMPT EVALUATION")
print(f"  Models: {list(MODELS.keys())}")
print(f"  Prompts: {list(PROMPTS.keys())}")
print(f"  Samples: 200 per model per prompt")
print("=" * 65)

# Create 200 sample evaluation subset
np.random.seed(SEED)
eval_idx = np.random.choice(len(df_test), size=200, replace=False)
eval_headlines = df_test.iloc[eval_idx][TEXT_COL].values
eval_labels = df_test.iloc[eval_idx][LABEL_COL].values

print(f"\nEval subset: {len(eval_headlines)} samples")
print(f"CB: {sum(eval_labels==1)} | Non-CB: {sum(eval_labels==0)}")

# ---- Store all prompt evaluation results ----
all_prompt_results = []

# ---- Loop through each model ----
for model_name, model_id in MODELS.items():

    print(f"\n{'#'*65}")
    print(f"#  Evaluating Prompts for: {model_name}")
    print(f"{'#'*65}")

    model_prompt_results = []

    # Test all 3 prompts
    for prompt_name, prompt_template in PROMPTS.items():

        result, preds, raw, unparseable = run_inference(
            eval_headlines,
            eval_labels,
            prompt_template,
            model_name,
            model_id,
            prompt_name
        )

        model_prompt_results.append(result)
        all_prompt_results.append(result)

        # Plot confusion matrix
        plot_cm(
            np.array(result['confusion_matrix']),
            model_name,
            prompt_name,
            result['accuracy']
        )

    # Print model summary
    print(f"\n  --- {model_name} Prompt Summary ---")
    print(f"  {'Prompt':<20} {'Accuracy':>9} {'F1 Macro':>9} {'Unparseable':>12}")
    print(f"  {'-'*55}")
    for r in model_prompt_results:
        print(f"  {r['prompt']:<20} {r['accuracy']:>8}% "
              f"{r['f1_macro']:>8}% {r['unparseable_rate']:>10}%")

# ---- Find Best Prompt Per Model ----
print(f"\n{'='*65}")
print("  BEST PROMPT PER MODEL")
print(f"{'='*65}")

best_prompts = {}

for model_name in MODELS.keys():
    model_results = [r for r in all_prompt_results if r['model_name'] == model_name]
    best = max(model_results, key=lambda x: x['f1_macro'])
    best_prompts[model_name] = {
        "prompt_name": best['prompt'],
        "prompt_template": PROMPTS[best['prompt']],
        "f1": best['f1_macro'],
        "accuracy": best['accuracy']
    }
    print(f"  {model_name}: {best['prompt']} "
          f"(Accuracy: {best['accuracy']}% | F1: {best['f1_macro']}%)")

# ---- Overall Best Prompt ----
# Find the prompt that performs best across both models
prompt_avg_f1 = {}
for prompt_name in PROMPTS.keys():
    scores = [r['f1_macro'] for r in all_prompt_results if r['prompt'] == prompt_name]
    prompt_avg_f1[prompt_name] = round(sum(scores) / len(scores), 2)

overall_best_prompt = max(prompt_avg_f1, key=prompt_avg_f1.get)

print(f"\n  Average F1 per prompt (across both models):")
for p, f1 in prompt_avg_f1.items():
    marker = " ← BEST" if p == overall_best_prompt else ""
    print(f"    {p}: {f1}%{marker}")

print(f"\n🏆 Overall Best Prompt: {overall_best_prompt}")

# Save prompt evaluation
pd.DataFrame(all_prompt_results).to_csv(
    f"{RESULTS_DIR}/prompt_evaluation.csv", index=False
)
print(f"\n✅ Prompt evaluation saved!")